name: Build KotakEngine
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Tady říkáme, aby chybu na Linuxu neřešil Windows
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Tady jsme dali v4

      - name: Install Node.js
        uses: actions/setup-node@v4 # Tady jsme dali v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Make application
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4 # Tady je ta nejdůležitější změna na v4
        with:
          name: KotakEngine-${{ matrix.os }}
          path: out/make/**/*
